### ISSUE TITLE
rmsgw installation

### ISSUE THREAD

**Issue by z3r0l1nk** [nwdigitalradio/n7nix#3]
In n7nix/rmsgw/install.sh on line 99 the script must download the rmsgw* package ending with **.tgz**, but at the source "http://76.5.53.198:800/docs/scripts/" the file is rmsgw-2.4.0-181.1.**tar.bz2**

**Comment by n7nix** [comment]
Fixed with commit 4352b4f. https://github.com/nwdigitalradio/n7nix/commit/4352b4f0413880178d61ca5cf66c6b50f5fe66f2
Made source tarball name extension a parameter & changed to bz2.
