### ISSUE TITLE
Typo in DIREWOLF_LOG_DIR

### ISSUE THREAD

**Issue by elafargue** [nwdigitalradio/n7nix#7]
Missing the "E" :)

https://github.com/nwdigitalradio/n7nix/blob/4d8eaae7b26a7ff2a9689f437610db89025c956f/systemd/install.sh#L152

**Comment by n7nix** [comment]
Thanks. Fixed in this commit.
https://github.com/nwdigitalradio/n7nix/commit/39ba260d73cf1fb0d40ca41ad518a9bcbef39424
